title: Ujjwal's DSA Notes
description: Collection of DSA problems and sheets
baseurl: "/dsa"
url: "https://gargujjwal.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Preserve directory structure
include:
  - "random-problems/**/*"
  - "sheets/**/*"

# Exclude these files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github
